# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('summary', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employer', models.CharField(max_length=32)),
            ],
        ),
    ]
