# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_auto_20170707_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default='Boston', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='minor',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='education',
            name='semester',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
