# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0003_auto_20170707_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 8, 0, 46, 31, 540000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
