# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0005_auto_20170707_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
