# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0006_auto_20170707_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='minor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_semester',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
