# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0007_auto_20170708_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='skills',
            field=models.TextField(default='n/a', max_length=5000),
            preserve_default=False,
        ),
    ]
