# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0009_generalinfo_privacy_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='privacy_policy',
        ),
    ]
