# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0010_remove_generalinfo_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='privacy_policy',
            field=models.TextField(default='n/a', max_length=5000),
            preserve_default=False,
        ),
    ]
